### ISSUE TITLE
Debug didauth issues in DEV

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#358]
On DEV, didauth has the following error when submitting a claim. The exact same request and payload works in a local environment.

```
INFO 2018-07-23 21:52:23,315 wallet 149 139955547883264 Wallet TheOrgBook_Holder_Wallet$$139955547883264 got verkey 8mYPW2VbiwFHhH992JCFtL1idjyEARGBRhHRFYZGxETE for existing DID FFdWd121MA5yrjZDAVNs7z
INFO 2018-07-23 21:52:23,331 wallet 149 139955547883264 Opened wallet TheOrgBook_Holder_Wallet$$139955547883264 on handle 5
INFO 2018-07-23 21:52:23,362 wallet 149 139955547883264 Created wallet TheOrgBook_Holder_Wallet$$139955547883264.seed2did on pool 2:the-org-book-holder-139955547883264
INFO 2018-07-23 21:52:23,363 wallet 149 139955547883264 Opened wallet TheOrgBook_Holder_Wallet$$139955547883264.seed2did on handle 6
INFO 2018-07-23 21:52:23,369 wallet 149 139955547883264 Removing wallet: TheOrgBook_Holder_Wallet$$139955547883264.seed2did
INFO 2018-07-23 21:52:23,388 wallet 149 139955547883264 Wallet TheOrgBook_Holder_Wallet$$139955547883264 got verkey 8mYPW2VbiwFHhH992JCFtL1idjyEARGBRhHRFYZGxETE for existing DID FFdWd121MA5yrjZDAVNs7z
WARNING 2018-07-23 21:52:23,414 libindy 149 139955547883264 _indy_loop_callback: Function returned error 404
INFO 2018-07-23 21:52:23,414 agents 149 139955547883264 HolderProver did not create link secret - it already exists
INFO 2018-07-23 21:52:23,925 agents 149 139955547883264 _AgentCore.get_schema: got schema SchemaKey(origin_did='6qnvgJtqwK44D8LFYnV5Yf', name='address.bc_registries', version='1.0.33') from ledger
WARNING 2018-07-23 21:52:24,114 indy 149 139955547883264 <<< Generate credential request
172.51.20.1 - - [23/Jul/2018:21:52:24 +0000] "POST /api/v2/indy/generate-credential-request HTTP/1.1" 200 2711 "-" "Python/3.6 aiohttp/3.3.2"
INFO 2018-07-23 21:52:24,209 auth 152 139955547883264 Authenticating DID...
DEBUG 2018-07-23 21:52:24,229 auth 152 139955547883264 Found verkey for DID 'did:sov:6qnvgJtqwK44D8LFYnV5Yf' in users table: 'b'/M\xb2d3\xb0\xb7>\x8f\x19\x7f\x83\x1fj$L\xb6\x99\xb2\x86\xc1\x07\xcfD\xbd\x92q\xd9\xfcw\x8d/''
ERROR 2018-07-23 21:52:24,229 exception 152 139955547883264 Internal Server Error: /api/v2/indy/store-credential
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/views.py", line 482, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/views.py", line 399, in initial
    self.perform_authentication(request)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/views.py", line 325, in perform_authentication
    request.user
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/request.py", line 222, in user
    self._authenticate()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/request.py", line 374, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/indy/api/auth.py", line 145, in authenticate
    verified = verify_signature(request)
  File "/home/indy/api/auth.py", line 190, in verify_signature
    raw_headers, path=path, method=request.method)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/didauth/headers.py", line 130, in verify
    message = generate_message(auth_headers, headers, method, path)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/didauth/utils.py", line 68, in generate_message
    raise Exception('Missing required header "%s"' % h)
Exception: Missing required header "cookie"
```

For now, didauth has been disabled.

"The cookie header is likely getting filtered out when the request is assembled. Not sure how it’s getting in there to begin with. I’d probably just change the library to always skip signing the cookie header. (The signature specifies that cookie is part of the signed headers but it’s not found in the request)" - Andrew

**Comment by swcurran** [comment]
Reassigning this to @cywolf to look at while looking at adding Basic Auth to the API for while we are in stealth mode.

**Comment by WadeBarnes** [comment]
For a starter on basic auth, have a look at what I did for https://github.com/bcgov/TheOrgBook/issues/338.  It's all controlled via env variables to turn on/off at the moment.
