### ISSUE TITLE
Can't run Quick Start Guide

### ISSUE THREAD

**Issue by dklesev** [bcgov/TheOrgBook#360]
When running the steps from "Quick Start Guide" I get following error in `permitify`:

```
permitify_bc_registries_1 exited with code 3
permitify_worksafe_bc_1 exited with code 3
permitify_liquor_control_and_licensing_branch_1 exited with code 3
permitify_city_of_surrey_1 exited with code 3
permitify_ministry_of_finance_1 exited with code 3
```

Additional Error description per service (seems to be similar in all the others):

**permitify_ministry_of_finance_1**
```
[2018-07-24 08:45:55 +0000] [78] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/indy/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/indy/von_connector/apps.py", line 134, in ready
    issuer_service_id = eventloop.do(run())
  File "/home/indy/von_connector/eventloop.py", line 24, in do
    return event_loop.run_until_complete(coro)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/indy/von_connector/apps.py", line 90, in run
    if jurisdiction['name'] == config['jurisdiction_name']:
TypeError: string indices must be integers
[2018-07-24 08:45:55 +0000] [78] [INFO] Worker exiting (pid: 78)
[2018-07-24 08:45:55 +0000] [1] [INFO] Shutting down: Master
[2018-07-24 08:45:55 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by nrempel** [comment]
We are in the process of updating permitify. Until then this is the expected result.

The update should be completed by the end of this week.

**Comment by dklesev** [comment]
The error seems to be away. But now I get this one:

```
tob-api_1        | ImportError: cannot import name 'VerifierException'
```

Is there something on my side or is it due to update being performed?

**Comment by dklesev** [comment]
Will there be any progress concerning the quick start?

**Comment by dklesev** [comment]
Hi @nrempel,

unfortunately I get following error (after step 10):

```
Creating network "permitify_vonx" with the default driver
Creating volume "permitify_caddy-data" with default driver
Creating volume "permitify_caddy-logs" with default driver
Creating volume "permitify_bcreg-agent-wallet" with default driver
Creating volume "permitify_ministry-finance-agent-wallet" with default driver
Creating volume "permitify_city-surrey-agent-wallet" with default driver
Creating volume "permitify_fraser-valley-agent-wallet" with default driver
Creating volume "permitify_liquor-control-agent-wallet" with default driver
Creating volume "permitify_worksafe-agent-wallet" with default driver
ERROR: No such service: bc_registries
``` 

It seems to be the case that the `manage` script is not properly updated (in permitify) as there are still following container names:

```
ALL_CONTAINERS="\
    bc_registries\
    worksafe_bc\
    ministry_of_finance\
    fraser_valley_health_authority\
    city_of_surrey\
    liquor_control_and_licensing_branch\
    redis \
    onbis\
"
```

In the compose file however there are different ones.

**Comment by swcurran** [comment]
Almost there.  Things are working for creating an incorp credential. The link to TheOrgBook is not working - need a caddyfile fix for that.  I'm not sure where the recipe page is - we'll find it  :-).

Nick was super sick today, so not all done.  We'll get it asap.

We will also fix the manage.sh/manage issue :-)

**Comment by nrempel** [comment]
Hi @dklesev, sorry for the delay.

The manage script has been fixed and a few other minor issues have been corrected so the demo should work now.

Can you make sure that you are running the latest of `master` from `von-network`, `TheOrgBook`, and `permitify` and try the steps again?

**Comment by dklesev** [comment]
Hi @nrempel,

I just tried to rerun the quickstart, now it seems to work.
But the guide is still misleading ([this](https://github.com/bcgov/TheOrgBook/blob/master/docker/README.md#quick-start-guide)) as `manage` of permitify doesn't have any `registerDids` command (f.e.). Steps 12 and 13 are not correct, too.
Thank you a lot for resolving the issue!

**Comment by swcurran** [comment]
Hi Dmitri - we'll get this cleaned up. The Quick Start Guide is now all in Permitify, so the one in TheOrgBook can be ignored. It will cover only starting TheOrgBook - as it should. Permitify has a dependency on TheOrgBook, not the other way around. As such, TheOrgBook shouldn't be talking about Permitify. We'll fix that.

Real Soon Now :-)

Stephen Curran
