### ISSUE TITLE
It is possible for the credential processor to fail when expiring existing credentials

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#410]
```
tob-wallet_1     | 172.21.0.3 - - [17/Aug/2018:21:04:03 +0000] "GET /api/v1/keyval/TheOrgBook_Holder_Wallet/credential/ff0b2787-1e0d-4dd1-ace4-ed9f5c46cfad/ HTTP/1.1" 200 2 "-" "reqwest/0.8.5"
tob-api_1        | DEBUG|indy::utils::proxy            |                 src/utils/proxy.rs:161 | Got response body []
tob-api_1        |  INFO|indy::utils::proxy            |                 src/utils/proxy.rs:251 | >>>>> Rest response array: []
tob-api_1        | ERROR|indy::services::wallet::remote|      src/services/wallet/remote.rs:301 | Got an error: NotFound("Error Item not found")
tob-api_1        | ERROR|indy::services::wallet::remote|      src/services/wallet/remote.rs:303 | Backtrace: stack backtrace:
tob-api_1        |    0:     0x7f7e23f7ca4c - backtrace::backtrace::trace::hdf42c48e4330a839
tob-api_1        |    1:     0x7f7e23f7b232 - backtrace::capture::Backtrace::new::hc8df8ff9f6f73d88
tob-api_1        |    2:     0x7f7e23c44246 - <indy::services::wallet::remote::RemoteWallet as indy::services::wallet::Wallet>::set::hc6fb103d11fa36f9
tob-api_1        |    3:     0x7f7e23c4e79b - indy::services::wallet::WalletService::set_object::h60acaf962c20814f
tob-api_1        |    4:     0x7f7e23aaad93 - indy::commands::anoncreds::prover::ProverCommandExecutor::execute::hb897463fdffd7a05
tob-api_1        |    5:     0x7f7e23c2bf3f - indy::commands::anoncreds::AnoncredsCommandExecutor::execute::h9a66f7aef8ffb0a7
tob-api_1        |    6:     0x7f7e23cbc600 - std::sys_common::backtrace::__rust_begin_short_backtrace::h395a2c32105f9d8b
tob-api_1        |    7:     0x7f7e23cbea72 - std::panicking::try::do_call::h7e47325e3ad42ae1
tob-api_1        |    8:     0x7f7e240c8a3e - __rust_maybe_catch_panic
tob-api_1        |                         at libpanic_unwind/lib.rs:102
tob-api_1        |    9:     0x7f7e23c62c49 - <F as alloc::boxed::FnBox<A>>::call_box::hdbf868344046d465
tob-api_1        |   10:     0x7f7e240be167 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h3a46ab40d44ff8db
tob-api_1        |                         at /checkout/src/liballoc/boxed.rs:794
tob-api_1        |                          - std::sys_common::thread::start_thread::heca3dbba8ff4f46a
tob-api_1        |                         at libstd/sys_common/thread.rs:24
tob-api_1        |   11:     0x7f7e240ad658 - std::sys::unix::thread::Thread::new::thread_start::ha1ecaaa6d3efa77d
tob-api_1        |                         at libstd/sys/unix/thread.rs:90
tob-api_1        |   12:     0x7f7e2fde26b9 - start_thread
tob-api_1        |   13:     0x7f7e2f40841c - clone
tob-api_1        |   14:                0x0 - <unknown>
tob-api_1        | DEBUG|indy::utils::proxy            |                 src/utils/proxy.rs:139 | Got response status 201 Created
tob-wallet_1     | 172.21.0.3 - - [17/Aug/2018:21:04:03 +0000] "POST /api/v1/keyval/ HTTP/1.1" 201 4277 "-" "reqwest/0.8.5"
tob-api_1        | DEBUG|indy::commands::anoncreds::prover|   src/commands/anoncreds/prover.rs:268 | store_credential <<< out_cred_id: "ff0b2787-1e0d-4dd1-ace4-ed9f5c46cfad"
tob-api_1        | TRACE|indy::api::anoncreds          |               src/api/anoncreds.rs:772 | indy_prover_store_credential: out_cred_id: "ff0b2787-1e0d-4dd1-ace4-ed9f5c46cfad"
tob-api_1        | TRACE|indy::api::wallet             |                  src/api/wallet.rs:266 | indy_close_wallet: >>> handle: 38
tob-api_1        | TRACE|indy::api::wallet             |                  src/api/wallet.rs:270 | indy_close_wallet: entities >>> handle: 38
tob-api_1        | TRACE|indy::api::wallet             |                  src/api/wallet.rs:284 | indy_close_wallet: <<< res: Success
tob-api_1        |  INFO|indy::commands                |                src/commands/mod.rs:122 | WalletCommand command received
tob-api_1        | DEBUG|indy::commands::wallet        |             src/commands/wallet.rs:171 | close >>> handle: 38
tob-api_1        | TRACE|indy::services::wallet        |         src/services/wallet/mod.rs:315 | close >>> handle: 38
tob-api_1        | TRACE|indy::services::wallet        |         src/services/wallet/mod.rs:322 | close <<< res: ()
tob-api_1        | DEBUG|indy::commands::wallet        |             src/commands/wallet.rs:175 | close << res: ()
tob-api_1        | TRACE|indy::api::wallet             |                  src/api/wallet.rs:277 | indy_close_wallet:
tob-api_1        | TRACE|indy::api::pool               |                    src/api/pool.rs:200 | indy_close_pool_ledger: >>> handle: 35
tob-api_1        | TRACE|indy::api::pool               |                    src/api/pool.rs:204 | indy_close_pool_ledger: entities >>> handle: 35
tob-api_1        | TRACE|indy::api::pool               |                    src/api/pool.rs:218 | indy_close_pool_ledger: <<< res: Success
tob-api_1        |  INFO|indy::commands                |                src/commands/mod.rs:114 | PoolCommand command received
tob-api_1        | DEBUG|indy::commands::pool          |               src/commands/pool.rs:182 | close >>> handle: 35
tob-api_1        | TRACE|indy::services::pool          |           src/services/pool/mod.rs:294 | zmq poll 1
tob-api_1        | TRACE|indy::services::pool          |           src/services/pool/mod.rs:311 | cmd [[101, 120, 105, 116], [41, 0, 0, 0]]
tob-api_1        | TRACE|indy::services::pool          |           src/services/pool/mod.rs:245 | process_actions - Pool work terminated
tob-api_1        |  INFO|indy::commands                |                src/commands/mod.rs:114 | PoolCommand command received
tob-api_1        | TRACE|indy::api::pool               |                    src/api/pool.rs:211 | indy_close_pool_ledger:
tob-api_1        | ERROR 2018-08-17 21:04:03,774 exception 151 140179950102272 Internal Server Error: /api/v2/indy/store-credential
tob-api_1        | Traceback (most recent call last):
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
tob-api_1        |     response = get_response(request)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
tob-api_1        |     response = self._get_response(request)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
tob-api_1        |     response = self.process_exception_by_middleware(e, request)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
tob-api_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
tob-api_1        |     return view_func(*args, **kwargs)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
tob-api_1        |     return self.dispatch(request, *args, **kwargs)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
tob-api_1        |     response = self.handle_exception(exc)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
tob-api_1        |     self.raise_uncaught_exception(exc)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
tob-api_1        |     response = handler(request, *args, **kwargs)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
tob-api_1        |     return func(*args, **kwargs)
tob-api_1        |   File "/home/indy/api_v2/decorators/jsonschema.py", line 25, in wrapper
tob-api_1        |     return func(request, *args, **kwargs)
tob-api_1        |   File "/home/indy/api_v2/views/indy.py", line 126, in store_credential
tob-api_1        |     credential_wallet_id = credential_manager.process()
tob-api_1        |   File "/home/indy/api_v2/indy/credential.py", line 210, in process
tob-api_1        |     credential_type, credential_wallet_id
tob-api_1        |   File "/home/indy/api_v2/indy/credential.py", line 435, in populate_application_database
tob-api_1        |     **existing_credential_query
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
tob-api_1        |     return getattr(self.get_queryset(), name)(*args, **kwargs)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 384, in get
tob-api_1        |     (self.model._meta.object_name, num)
tob-api_1        | api_v2.models.Credential.MultipleObjectsReturned: get() returned more than one Credential -- it returned 2!
tob-api_1        | 172.19.0.7 - - [17/Aug/2018:21:04:03 +0000] "POST /api/v2/indy/store-credential HTTP/1.1" 500 15934 "-" "Python/3.6 aiohttp/3.3.2"
```

Somehow extra credentials are getting into database without previous ones being expired. Subsequent queries for a single non-expired credential fail since there is more than one.

This state could be possible by having TOB crash partway through processing. Or maybe having an invalid config and then changing it to something different.

Likely we need a transaction to prevent this.

**Comment by nrempel** [comment]
It sounds like @cywolf has a solution for this which will be a part of the 1.6 release.
