### ISSUE TITLE
Periodic Errors Posting to TOB

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#627]
I am getting periodic errors posting to TOB, with data that works when I re-try.

For example see attached "test-creds-batch.json".  When I post this using Postman, it is successful and all credentials are saved to TOB.

When I ran the full conversion, I get the following error for corp "FM0078822":

[31mtob-api_1      |[0m INFO 2018-10-27 01:05:38,915 base 9 140162782975744 _BaseAnchor.get_cred_def: got cred def for 6qnvgJtqwK44D8LFYnV5Yf:3:CL:8:tag from cache
[31mtob-api_1      |[0m WARNING 2018-10-27 01:05:38,919 credential 9 140160553449216 <<< store cred in local database: 0.18470390001311898
[31mtob-api_1      |[0m INFO 2018-10-27 01:05:38,927 base 9 140162782975744 _BaseAnchor.get_cred_def: got cred def for 6qnvgJtqwK44D8LFYnV5Yf:3:CL:8:tag from cache
[31mtob-api_1      |[0m ERROR 2018-10-27 01:05:38,933 web_protocol 9 140163059152640 Error handling request
[31mtob-api_1      |[0m Traceback (most recent call last):
[31mtob-api_1      |[0m   File "/home/indy/api_v2/indy/credential.py", line 443, in populate_application_database
[31mtob-api_1      |[0m     source_id=topic_source_id, type=topic_type
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
[31mtob-api_1      |[0m     return getattr(self.get_queryset(), name)(*args, **kwargs)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
[31mtob-api_1      |[0m     self.model._meta.object_name
[31mtob-api_1      |[0m api_v2.models.Topic.DoesNotExist: Topic matching query does not exist.
[31mtob-api_1      |[0m 
[31mtob-api_1      |[0m During handling of the above exception, another exception occurred:
[31mtob-api_1      |[0m 
[31mtob-api_1      |[0m Traceback (most recent call last):
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
[31mtob-api_1      |[0m     return self.cursor.execute(sql, params)
[31mtob-api_1      |[0m psycopg2.IntegrityError: duplicate key value violates unique constraint "topic_source_id_type_d2b31a6e_uniq"
[31mtob-api_1      |[0m DETAIL:  Key (source_id, type)=(FM0078822, registration) already exists.
[31mtob-api_1      |[0m 
[31mtob-api_1      |[0m 
[31mtob-api_1      |[0m The above exception was the direct cause of the following exception:
[31mtob-api_1      |[0m 
[31mtob-api_1      |[0m Traceback (most recent call last):
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
[31mtob-api_1      |[0m     resp = await self._request_handler(request)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
[31mtob-api_1      |[0m     resp = await handler(request)
[31mtob-api_1      |[0m   File "/home/indy/tob_anchor/views.py", line 208, in store_credential
[31mtob-api_1      |[0m     client, indy_holder_id(), params, processor, issuer_did)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 293, in perform_store_credential
[31mtob-api_1      |[0m     stored_row, ret_row = proc.result()
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 268, in _store_credential
[31mtob-api_1      |[0m     await processor.process_credential_async(stored, origin_did, batch_info)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 64, in process_credential_async
[31mtob-api_1      |[0m     return await asyncio.wrap_future(fut)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
[31mtob-api_1      |[0m     result = self.fn(*self.args, **self.kwargs)
[31mtob-api_1      |[0m   File "/home/indy/tob_anchor/boot.py", line 112, in run_django_proc
[31mtob-api_1      |[0m     return proc(*args)
[31mtob-api_1      |[0m   File "/home/indy/tob_anchor/processor.py", line 63, in proc
[31mtob-api_1      |[0m     return credential_manager.process(cred, origin_did)
[31mtob-api_1      |[0m   File "/home/indy/api_v2/indy/credential.py", line 374, in process
[31mtob-api_1      |[0m     return self.populate_application_database(credential_type, credential)
[31mtob-api_1      |[0m   File "/home/indy/api_v2/indy/credential.py", line 447, in populate_application_database
[31mtob-api_1      |[0m     source_id=topic_source_id, type=topic_type
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
[31mtob-api_1      |[0m     return getattr(self.get_queryset(), name)(*args, **kwargs)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
[31mtob-api_1      |[0m     obj.save(force_insert=True, using=self.db)
[31mtob-api_1      |[0m   File "/home/indy/api_v2/models/Topic.py", line 40, in save
[31mtob-api_1      |[0m     super(Topic, self).save(*args, **kwargs)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
[31mtob-api_1      |[0m     force_update=force_update, update_fields=update_fields)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
[31mtob-api_1      |[0m     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
[31mtob-api_1      |[0m     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
[31mtob-api_1      |[0m     using=using, raw=raw)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
[31mtob-api_1      |[0m     return getattr(self.get_queryset(), name)(*args, **kwargs)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 1079, in _insert
[31mtob-api_1      |[0m     return query.get_compiler(using=using).execute_sql(return_id)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
[31mtob-api_1      |[0m     cursor.execute(sql, params)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
[31mtob-api_1      |[0m     return super(CursorDebugWrapper, self).execute(sql, params)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
[31mtob-api_1      |[0m     return self.cursor.execute(sql, params)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
[31mtob-api_1      |[0m     six.reraise(dj_exc_type, dj_exc_value, traceback)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
[31mtob-api_1      |[0m     raise value.with_traceback(tb)
[31mtob-api_1      |[0m   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
[31mtob-api_1      |[0m     return self.cursor.execute(sql, params)
[31mtob-api_1      |[0m django.db.utils.IntegrityError: duplicate key value violates unique constraint "topic_source_id_type_d2b31a6e_uniq"
[31mtob-api_1      |[0m DETAIL:  Key (source_id, type)=(FM0078822, registration) already exists.
[31mtob-api_1      |[0m 
[31mtob-api_1      |[0m INFO 2018-10-27 01:05:38,961 base 9 140162782975744 _BaseAnchor.get_cred_def: got cred def for 6qnvgJtqwK44D8LFYnV5Yf:3:CL:8:tag from cache
[31mtob-api_1      |[0m INFO 2018-10-27 01:05:39,028 base 9 140162782975744 _BaseAnchor.get_cred_def: got cred def for 6qnvgJtqwK44D8LFYnV5Yf:3:CL:8:tag from cache

**Comment by ianco** [comment]
Here is the json of the credential batch, for some reason I can't attach a json file:

[
    {
        "attributes": {
            "effective_date": "2004-03-06T08:00:00+00:00",
            "entity_name": "MOLLIE'S STATIONERY",
            "entity_name_effective": "2004-03-06T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2004-03-06T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2004-03-06T08:00:00+00:00",
            "registration_id": "FM0367191",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2005-02-23T08:00:00+00:00",
            "entity_name": "JUMBO ACCOMMODATION",
            "entity_name_effective": "2005-02-23T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2005-02-23T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2005-02-23T08:00:00+00:00",
            "registration_id": "FM0391102",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2003-09-15T07:00:00+00:00",
            "entity_name": "MODERN DOG",
            "entity_name_effective": "2003-09-15T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2003-09-15T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2003-09-15T07:00:00+00:00",
            "registration_id": "FM0355397",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2004-11-25T08:00:00+00:00",
            "entity_name": "MAEVA BOUTIQUE COMFORT SHOES",
            "entity_name_effective": "2004-11-25T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2004-11-25T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2004-11-25T08:00:00+00:00",
            "registration_id": "FM0385263",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1998-11-16T08:00:00+00:00",
            "entity_name": "WINDERMERE FLEMMER & ASSOCIATES REALTY PLUS",
            "entity_name_effective": "1998-11-16T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1998-11-16T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "1998-11-16T08:00:00+00:00",
            "registration_id": "FM0249563",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1985-06-13T07:00:00+00:00",
            "entity_name": "UNIQUE TRANSPORTATION",
            "entity_name_effective": "1985-06-13T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1985-06-13T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "1985-06-13T07:00:00+00:00",
            "registration_id": "FM0061888",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2000-12-01T08:00:00+00:00",
            "entity_name": "SPECIAL PURCHASE ONLY",
            "entity_name_effective": "2000-12-01T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2000-12-01T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2000-12-01T08:00:00+00:00",
            "registration_id": "FM0291940",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2005-11-01T08:00:00+00:00",
            "entity_name": "LACKNER MCLENNAN INSURANCE BROKERS",
            "entity_name_effective": "2005-11-01T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2005-11-01T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2005-11-01T08:00:00+00:00",
            "registration_id": "FM0409810",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2007-05-07T07:00:00+00:00",
            "entity_name": "STAR OF INDIA FINE CUISINE",
            "entity_name_effective": "2007-05-07T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2007-05-07T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2007-05-07T07:00:00+00:00",
            "registration_id": "FM0450291",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1997-03-19T08:00:00+00:00",
            "entity_name": "GOLDEN MILE CELLARS",
            "entity_name_effective": "1997-03-19T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1997-03-19T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "1997-03-19T08:00:00+00:00",
            "registration_id": "FM0216496",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1987-06-05T07:00:00+00:00",
            "entity_name": "CRANBROOK TRI-STAR SALES",
            "entity_name_effective": "1987-06-05T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1987-06-05T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "1987-06-05T07:00:00+00:00",
            "registration_id": "FM0078822",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1988-05-04T18:42:55+00:00",
            "entity_name": "NORTH SHORE MARKETING GROUP",
            "entity_name_effective": "1988-05-04T18:42:55+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1987-06-05T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "Entity Name Event: CONVFMNC",
            "registered_jurisdiction": "",
            "registration_date": "1987-06-05T07:00:00+00:00",
            "registration_id": "FM0078822",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1990-01-08T08:00:00+00:00",
            "entity_name": "TRUEMAN SECURITY",
            "entity_name_effective": "1990-01-08T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1990-01-08T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "1990-01-08T08:00:00+00:00",
            "registration_id": "FM0103774",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2007-02-01T08:00:00+00:00",
            "entity_name": "PREMIER TENT RENTAL",
            "entity_name_effective": "2007-02-01T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2007-02-01T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2007-02-01T08:00:00+00:00",
            "registration_id": "FM0442777",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2008-08-05T07:00:00+00:00",
            "entity_name": "ROLLING THUNDER WATER SAVING SOLUTIONS",
            "entity_name_effective": "2008-08-05T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2008-08-05T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2008-08-05T07:00:00+00:00",
            "registration_id": "FM0483509",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1990-01-29T08:00:00+00:00",
            "entity_name": "CENTENNIAL FOODSERVICE",
            "entity_name_effective": "1990-01-29T08:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1990-01-29T08:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "1990-01-29T08:00:00+00:00",
            "registration_id": "FM0104404",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1977-05-09T07:00:00+00:00",
            "entity_name": "NEW CONCEPT HOMES",
            "entity_name_effective": "1977-05-09T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1977-05-09T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "1977-05-09T07:00:00+00:00",
            "registration_id": "FM0023439",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2008-07-17T07:00:00+00:00",
            "entity_name": "KJCL CONSTRUCTION",
            "entity_name_effective": "2008-07-17T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2008-07-17T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2008-07-17T07:00:00+00:00",
            "registration_id": "FM0482351",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "2010-10-20T07:00:00+00:00",
            "entity_name": "SUSSEX INSURANCE AGENCY (WESTWOOD MALL)",
            "entity_name_effective": "2010-10-20T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "2010-10-20T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "2010-10-20T07:00:00+00:00",
            "registration_id": "FM0541083",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    },
    {
        "attributes": {
            "effective_date": "1982-09-02T07:00:00+00:00",
            "entity_name": "JAMES BAY TEAROOM AND RESTAURANT",
            "entity_name_effective": "1982-09-02T07:00:00+00:00",
            "entity_status": "ACT",
            "entity_status_effective": "1982-09-02T07:00:00+00:00",
            "entity_type": "Sole Proprietorship",
            "home_jurisdiction": "BC",
            "reason_description": "State Event: CONVFMREGI, Entity Name Event: CONVFMREGI",
            "registered_jurisdiction": "",
            "registration_date": "1982-09-02T07:00:00+00:00",
            "registration_id": "FM0043794",
            "registration_type": ""
        },
        "schema": "registration.bc_registries",
        "version": "1.0.36"
    }
]

**Comment by ianco** [comment]
There is about a 5% failure rate posting credentials to TOB, and it's random (when I re-ran the entire data load the above corp 'FM0078822' credentials processed successfully.

**Comment by cywolf** [comment]
I managed to trigger this once yesterday, I think we can avoid it by just catching the exception and looking up the Topic in that case (since it's just been created). Need to do the same when creating a credential set.

**Comment by ianco** [comment]
After running for several hours the error rate is up to almost 50% (162000 processed, including 72000 errors).  Same error repeating.

api_v2.models.Topic.DoesNotExist: Topic matching query does not exist.

**Comment by nrempel** [comment]
When was the first time we saw these errors? As far as I know, the last credential issuance run didn't have any issues?

Or is this a new dataset?

**Comment by cywolf** [comment]
The fix I added is on the feature/credential-set branch, you may want to try that one (with a reprocess or blank DB).

**Comment by ianco** [comment]
@nrempel  The errors started Friday after I updated my local TOB.  (I had also just done some updates to BC-Reg but these look like TOB errors, since it is inconsistent and the data itself looks good.)

I'll try @cywolf 's fix ...

**Comment by ianco** [comment]
Still getting some errors - 109,000 credentials posted, 38 errors

**Comment by ianco** [comment]
Ran a test overnight, posted 366k credentials, 115 errors occurred.  Same error message as before.  I think that when one corp errors out it fails the whole batch, because the errors seem to occur in batches.  When I re-set the status of these credentials to "not processed" they submitted successfully.

ERROR 2018-10-31 03:55:05,697 web_protocol 10 140141602289408 Error handling request
Traceback (most recent call last):
 File "/home/indy/api_v2/indy/credential.py", line 404, in find_or_create_topic
  return Topic.objects.get(**topic_spec)
 File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
  return getattr(self.get_queryset(), name)(*args, **kwargs)
 File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
 api_v2.models.Topic.DoesNotExist: Topic matching query does not exist.

**Comment by WadeBarnes** [comment]
Here are a couple more that were encountered during testing today;
```
ERROR 2018-11-13 20:43:58,367 web_protocol 1 140362391045888 Error handling request
Traceback (most recent call last):
  File "/home/indy/api_v2/indy/credential.py", line 404, in find_or_create_topic
    return Topic.objects.get(**topic_spec)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
api_v2.models.Topic.DoesNotExist: Topic matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/indy/tob_anchor/views.py", line 208, in store_credential
    client, indy_holder_id(), params, processor, issuer_did)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 293, in perform_store_credential
    stored_row, ret_row = proc.result()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 268, in _store_credential
    await processor.process_credential_async(stored, origin_did, batch_info)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 64, in process_credential_async
    return await asyncio.wrap_future(fut)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/indy/tob_anchor/boot.py", line 112, in run_django_proc
    return proc(*args)
  File "/home/indy/tob_anchor/processor.py", line 63, in proc
    return credential_manager.process(cred, origin_did)
  File "/home/indy/api_v2/indy/credential.py", line 382, in process
    return self.populate_application_database(credential_type, credential)
  File "/home/indy/api_v2/indy/credential.py", line 690, in populate_application_database
    topic, related_topic = cls.resolve_credential_topics(credential, processor_config)
  File "/home/indy/api_v2/indy/credential.py", line 476, in resolve_credential_topics
    topic = cls.find_or_create_topic(topic_spec)
  File "/home/indy/api_v2/indy/credential.py", line 407, in find_or_create_topic
    return Topic.objects.create(**topic_spec)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/indy/api_v2/models/Topic.py", line 38, in save
    self.full_clean()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/base.py", line 1250, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'__all__': ['Topic with this Source id and Type already exists.']}
```

```
ERROR 2018-11-13 20:35:00,558 web_protocol 1 139896621000448 Error handling request
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
psycopg2.OperationalError: could not seek to end of file "base/32770/33493": Input/output error
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."credential_set" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/indy/tob_anchor/views.py", line 208, in store_credential
    client, indy_holder_id(), params, processor, issuer_did)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 293, in perform_store_credential
    stored_row, ret_row = proc.result()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 268, in _store_credential
    await processor.process_credential_async(stored, origin_did, batch_info)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/web/view_helpers.py", line 64, in process_credential_async
    return await asyncio.wrap_future(fut)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/indy/tob_anchor/boot.py", line 112, in run_django_proc
    return proc(*args)
  File "/home/indy/tob_anchor/processor.py", line 63, in proc
    return credential_manager.process(cred, origin_did)
  File "/home/indy/api_v2/indy/credential.py", line 382, in process
    return self.populate_application_database(credential_type, credential)
  File "/home/indy/api_v2/indy/credential.py", line 748, in populate_application_database
    cls.create_search_models(dbCredential, processor_config)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/transaction.py", line 223, in __exit__
    connection.commit()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: could not seek to end of file "base/32770/33493": Input/output error
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."credential_set" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
```
